### ISSUE TITLE
Cannot customize dropdown panel color for `gr-select`

### ISSUE THREAD

**Issue by dermotduffy** [paqtcom/graphite-design-system#133]
Hello,

Is it possible to set the color of the dropdown menu for `gr-select`?

I think not, as:

```
gr-select ->
  gr-dropdown
```

and `gr-dropdown` in its css `:host` selector has:

```
  --panel-background-color: var(--gr-color-white);
```

so even setting `--panel-background-color` from the outside of the `gr-select` component will have no impact on the underlying dropdown. Notice the white bars in the below:

<img width="297" alt="Screen Shot 2023-02-06 at 6 44 38 PM" src="https://user-images.githubusercontent.com/1136829/217134730-cd0ac6b0-8589-4808-a248-d9aae11b60c7.png">

... even though the following variables are set at the top level:

```css
gr-select,
gr-menu-item,
gr-dropdown,
gr-menu {
  --panel-background-color: var(--primary-background-color);
  --background-color: var(--primary-background-color);
  --background-color-hover: var(--secondary-background-color);
  --background-color-focus: var(--secondary-background-color);
  --color: var(--primary-text-color);
}
```
